controllers/CategoryController.php
<?php

namespace app\controllers;
use app\models\Category;
use app\models\Products;
use yii\data\Pagination;
use app\models\Users;
use Yii;

class CategoryController extends AppController
{
     public function actionIndex(){
          return $this->render('index');
     }

     public function actionView(){
          $id = Yii::$app->request->get('id');
          $db = Category::findOne([
               'id' => $id
          ]);
          if(empty($db))
               throw new \yii\web\HttpException(404, 'Bunday malumotlar mavjud emas!');
          $query = Products::find()
               ->where(['category_id' => $id]);
          $page = new Pagination([
             'totalCount' => $query->count(),
             'pageSize' => 9,
             'forcePageParam' => false,
             'pageSizeParam' => false
          ]);
          $products = $query->offset($page->offset)
               ->limit($page->limit)
               ->all();
          return $this->render('view', compact('db', 'products', 'page'));
     }

     public function actionContact(){
          $users = new Users;
          if($users->load(Yii::$app->request->post())){
               $u = Users::find()
                    ->where(['login' => $users->login])
                    ->all();
               if(!empty($u)){
                    return $this->refresh();
               }
               else{
                    if($users->save()){
                         throw new \yii\web\HttpException(404, 'Royxatdan otib oldingiz! Login va Parol orqali kabinetingizga kirish imkoni mavjud! Login va parolni unutmang!');
                    }
                    else{
                         throw new \yii\web\HttpException(404, 'Malumotlar saqlanmadi!');
                    }

               }
          }
          else{
               return $this->render('contact', compact('users'));
          }
          return $this->render('contact', compact('users'));
     }

     public function actionIsLogin(){
          $login = Yii::$app->request->get('login');
          $users = Users::findOne(['login' => $login]);
          if(!empty($users)) return true;
          else return false;
     }

     public function actionLogin(){
          $model = new Users;
          if($model->load(Yii::$app->request->post())){
               $model->isAuth($model->username, $model->password);
          }
          return $this->render('login', compact('model'));
     }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error container">
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

</div>

views/site/login.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<!-- Page Breadcrumb Start -->
<div class="main-breadcrumb mb-100" style="background: rgba(0, 0, 0, 0) url(<?=Url::base()?>/img/blog/5.png) no-repeat scroll center center / cover;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="breadcrumb-content text-center ptb-70">
                    <ul class="breadcrumb-list breadcrumb">
                        <li><a href="<?=Url::home(); ?>">Bosh sahifa</a></li>
                        <li><a href="<?=Url::to(['category/contact']);?>">Registratsiya</a></li>
                        <li><a href="">Kirish</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>
<!-- Page Breadcrumb End -->
<!-- LogIn Page Start -->
<div class="log-in pb-100">
    <div class="container">
        <div class="row">
            <!-- New Customer Start -->
            <div class="col-sm-6">
                <div class="well">
                    <div class="new-customer">
                        <h3>NEW CUSTOMER</h3>
                        <p class="mtb-10"><strong>Register</strong></p>
                        <p>By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made</p>
                        <a class="customer-btn" href="register.html">continue</a>
                    </div>
                </div>
            </div>
            <!-- New Customer End -->
            <!-- Returning Customer Start -->
            <div class="col-sm-6">
                <div class="well">
                    <div class="return-customer">
                        <p class="mb-10">Login va Parol orqali kabinet kirish</p>
                         <?php
                         $form = ActiveForm::begin(); ?>

                         <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                         <?= $form->field($model, 'password')->passwordInput() ?>

                         <?= $form->field($model, 'rememberMe')->checkbox([
                              'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
                         ]) ?>

                        <div class="form-group">
                            <div class="col-lg-offset-1 col-lg-11">
                                 <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                            </div>
                        </div>

                         <?php ActiveForm::end();
                         ?>
                    </div>
                </div>
            </div>
            <!-- Returning Customer End -->
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>
<!-- LogIn Page End -->